### ISSUE TITLE
File handling causes TypeError: argument string is required

### ISSUE THREAD

**Issue by andreasnett** [adonisjs/bodyparser#31]
This error was first reported  [here](https://github.com/adonisjs/bodyparser/issues/28).
I currently have an app in production that constantly gets 502 because the backend crashes. For me this is very urgent.

If I can help I will. Need a description of what is wrong and where and I can make a pull request.

## Package version
 "@adonisjs/ace": "^5.0.8",
    "@adonisjs/auth": "^3.0.7",
    "@adonisjs/bodyparser": "^2.0.5",
    "@adonisjs/cors": "^1.0.7",
    "@adonisjs/drive": "^1.0.4",
    "@adonisjs/fold": "^4.0.9",
    "@adonisjs/framework": "^5.0.9",
    "@adonisjs/ignitor": "^2.0.8",
    "@adonisjs/lucid": "^6.1.3",
    "@adonisjs/mail": "^3.0.10",
    "@adonisjs/validator": "^5.0.6"

## Node.js and npm version
node v12.16.2
npm v6.14.4

## Sample Code (to reproduce the issue)

```
const file = request.file("image");

if (file && !(file.tmpPath == null)) {
    const res = await Cloudinary.v2.uploader.upload(file.tmpPath, {
    folder: "profile_pictures",
});
user.image_url = res.secure_url;
await network.users().save(user);
```

**Comment by danpospisil** [comment]
I have exactly the same issue - without setting content-type header my app will crash. The stack trace is following:
```
TypeError: argument string is required
    at Object.parse (/mnt/c/wamp64/www/mhub/node_modules/media-typer/index.js:141:11)
    at new File (/mnt/c/wamp64/www/mhub/node_modules/@adonisjs/bodyparser/src/Multipart/File.js:147:36)
    at Multipart.onPart (/mnt/c/wamp64/www/mhub/node_modules/@adonisjs/bodyparser/src/Multipart/index.js:129:26)
    at Form.<anonymous> (/mnt/c/wamp64/www/mhub/node_modules/@adonisjs/bodyparser/src/Multipart/index.js:171:14)
    at Form.emit (events.js:310:20)
    at Form.EventEmitter.emit (domain.js:482:12)
    at Object.cb (/mnt/c/wamp64/www/mhub/node_modules/multiparty/index.js:642:10)
    at flushEmitQueue (/mnt/c/wamp64/www/mhub/node_modules/multiparty/index.js:626:10)
    at /mnt/c/wamp64/www/mhub/node_modules/multiparty/index.js:602:5
    at handlePart (/mnt/c/wamp64/www/mhub/node_modules/multiparty/index.js:641:3)
    at Form.onParseHeadersEnd (/mnt/c/wamp64/www/mhub/node_modules/multiparty/index.js:527:5)
    at Form._write (/mnt/c/wamp64/www/mhub/node_modules/multiparty/index.js:319:24)
    at doWrite (_stream_writable.js:442:12)
    at writeOrBuffer (_stream_writable.js:426:5)
    at Form.Writable.write (_stream_writable.js:317:11)
    at IncomingMessage.ondata (_stream_readable.js:695:22)
```
And I dont see any way how to catch the exception. So basically this can lead to DoS attack quite easily.

**Comment by thetutlage** [comment]
Lemme look into it and get the fix out

**Comment by AmosKorir** [comment]
Facing the same issue, when uploading a file from android application
