### ISSUE TITLE
Can't getUrl from a private s3 bucket

### ISSUE THREAD

**Issue by SergioVago** [adonisjs/bodyparser#59]
https://github.com/adonisjs/bodyparser/blob/6e7cf68edba9ddae39cc7d7be1ab7665e18919d9/src/Multipart/File.ts#L253

**Comment by Julien-R44** [comment]
Can you please make a little effort and give more information about the problem you are facing?

**Comment by SergioVago** [comment]
Sure. 

A have this code for upload some file on S3 Bucket
```js
const { account_id: accountId } = request.only(['account_id'])
const file = request.file('file')

if (!file) {
    return
}

const name = uuid() + '-' + file.clientName

const createdFile = await AccountFile.create({
    name,
    accountId,
})

await file.moveToDisk(
    'accounts-files',
    {
        name,
    },
    Env.get('DRIVE_DISK')
)
```

I checked my bucket and i have the file uploaded, but have this error on my catch
```js
 err: {
      "type": "TypeError",
      "message": "this.adapter.config.endpoint is not a function",
      "stack":
          TypeError: this.adapter.config.endpoint is not a function
              at S3Driver.getUrl (D:\Github\app-v1\server\node_modules\@adonisjs\drive-s3\build\src\Drivers\S3.js:220:66)
              at File.moveToDisk (D:\Github\app-v1\server\node_modules\@adonisjs\bodyparser\build\src\Multipart\File.js:177:44)
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
              at AccountFilesController.store (D:\Github\app-v1\server\app\Controllers\Http\AccountFilesController.ts:25:5)
              at Object.PreCompiler.runRouteHandler [as fn] (D:\Github\app-v1\server\node_modules\@adonisjs\http-server\build\src\Server\PreCompiler\index.js:47:31)
              at UserTypeLimiter.handle (D:\Github\app-v1\server\app\Middleware\UserTypeLimiter.ts:55:5)
              at AuthMiddleware.handle (D:\Github\app-v1\server\app\Middleware\Auth.ts:87:5)
              at Server.handleRequest (D:\Github\app-v1\server\node_modules\@adonisjs\http-server\build\src\Server\index.js:108:13)
      "status": 500
    }
```

My bucket is a private bucket, so I suspect that method getUrl is the problem, because we need to use getSignedUrl in this case

Locally this code is working with a DRIVE_DISK=local
